# Generated by Django 3.2.5 on 2021-10-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latest_news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='number',
            field=models.PositiveIntegerField(blank=True, db_index=True, unique=True),
        ),
    ]
